### ISSUE TITLE
fieldset border

### ISSUE THREAD

**Issue by mxlav** [wet-boew/wet-boew-drupal#500]
The `fieldset` no longer has a border around all the fields contained within it. Also it has a line under the legend caused by `legend:after border-top: 1px solid #CCCCCC;` which looks odd.

**Comment by sylus** [comment]
Yeah WET is overriding the default drupal style for this. Taking a look :)

**Comment by sylus** [comment]
I added some new code that will run on the node edit and add screen. Sass looks as follows:

``` scss
.page-node-add,
.page-node-edit {
  fieldset {
    border: 1px solid #ccc;
    padding: 2.5em 0 0 0; /* LTR */
    position: relative;
    margin: 1em 0;
    legend { height: 0px }
    .fieldset-legend {
      margin-top: 0.5em;
      padding-left: 15px; /* LTR */
      position: absolute;
      text-transform: uppercase;
    }
    .fieldset-wrapper { padding: 0 13px 13px 15px; /* LTR */ }
    fieldset.collapsed { background-color: transparent; }
    fieldset {
      background-color: #fff;
      fieldset { background-color: #f8f8f8; }
    }
  }
}

html.js .page-node-add,
html.js .page-node-edit {
  fieldset.collapsed {
    border-width: 1px;
    height: auto;
  }
}
```
