### ISSUE TITLE
Reduce specificity on CSS rules for theme-base

### ISSUE THREAD

**Issue by minorOffense** [wet-boew/wet-boew-drupal#912]
This is more of a general task than a specific issue, but there seem to be several cases where the specificity in the style sheets for the theme-base components (theme.css / theme-min.css) are set unnecessarily high.

Ex:

``` css
#base-fullhd ul li#base-fullhd-lang a {
    margin-right: 1px;
    padding-right: 10px;
}
```

Embedding ID elements inside other ID elements should be avoided as much as possible as it make it difficult for another rules to supersede this rule.

**Comment by minorOffense** [comment]
Another example

``` css
#base-srchbx #base-srch {
    background: none repeat scroll 0 0 #FFFFFF;
    border: 1px solid #CCCCCC;
    border-radius: 2px 2px 2px 2px;
    box-shadow: none;
    color: #444444;
    margin-left: 0;
    padding: 2px 0;
    width: 218px;
}
```
